openapi: 3.1.0
info:
  title: Aurora CRUDL API
  version: 1.0.0

paths:
  /create-item:
    post:
      operationId: createItemHandler
      summary: "Handle item create requests."
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/requestSchemes/createItemHandler'
      responses:
        201:
          description: "Successful response."
          content:
            application/json:
              schema:
                $ref: '#/components/responseSchemes/createItemHandler'
  /read-item/{id}:
    get:
      operationId: readItemHandler
      summary: "Handle item read requests."
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: "Item Id."
            format: uuid
      responses:
        200:
          description: "Successful response."
          content:
            application/json:
              schema:
                $ref: '#/components/responseSchemes/readItemHandler'
  /update-item/{id}:
    patch:
      operationId: updateItemHandler
      summary: "Handle item update requests."
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: "Item Id."
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/requestSchemes/updateItemHandler'
      responses:
        200:
          description: "Successful response."
          content:
            application/json:
              schema:
                $ref: '#/components/responseSchemes/updateItemHandler'
  /delete-item/{id}:
    delete:
      operationId: deleteItemHandler
      summary: "Handle item delete requests."
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: "Item Id."
            format: uuid
      responses:
        200:
          description: "Successful response."
          content:
            application/json:
              schema:
                $ref: '#/components/responseSchemes/deleteItemHandler'
  /list-items:
    get:
      operationId: listItemsHandler
      summary: "Handle item list requests."
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            description: "Page number."
            minimum: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            description: "Page limit."
            minimum: 1
            maximum: 10
      responses:
        200:
          description: "Successful response."
          content:
            application/json:
              schema:
                $ref: '#/components/responseSchemes/listItemsHandler'

components:
  requestSchemes:
    createItemHandler:
      type: object
      description: "Expected HTTP body payload."
      additionalProperties: false
      properties:
        name:
          type: string
          description: "Item name."
          minLength: 1
          maxLength: 16
        description:
          type: string
          description: "Item description."
          minLength: 1
          maxLength: 128
        category:
          type: object
          description: "Item category."
          additionalProperties: false
          properties:
            name:
              type: string
              description: "Category name."
              minLength: 1
              maxLength: 32
            description:
              type: string
              description: "Category description."
              minLength: 1
              maxLength: 128
          required:
            - name
      required:
        - name
    updateItemHandler:
      type: object
      description: "Expected HTTP body payload."
      additionalProperties: false
      properties:
        name:
          type: string
          description: "New item name."
          minLength: 1
          maxLength: 16
        description:
          type: string
          description: "New item description."
          minLength: 1
          maxLength: 128
        category:
          type: object
          description: "Item category."
          additionalProperties: false
          properties:
            name:
              type: string
              description: "New category name."
              minLength: 1
              maxLength: 32
            description:
              type: string
              description: "New category description."
              minLength: 1
              maxLength: 128
          required:
            - name

  responseSchemes:
    createItemHandler:
      type: object
      description: "HTTP body payload."
      additionalProperties: false
      properties:
        item_id:
          type: string
          description: "Created item Id."
        category_id:
          type: string
          description: "Created category Id."
      required:
        - item_id
    readItemHandler:
      type: object
      description: "HTTP body payload."
      additionalProperties: false
      properties:
        name:
          type: string
          description: "Item name."
        description:
          type: string
          description: "Item description."
        category_name:
          type: string
          description: "Item category name."
        category_description:
          type: string
          description: "Item category description."
      required:
        - name
    updateItemHandler:
      type: object
      description: "HTTP body payload."
      additionalProperties: false
      properties:
        name:
          type: string
          description: "Old item name."
        description:
          type: string
          description: "Old or current item description."
        category_name:
          type: string
          description: "Old or current item category name."
        category_description:
          type: string
          description: "Old or current item category description."
      required:
        - name
    deleteItemHandler:
      type: object
      description: "HTTP body payload."
      additionalProperties: false
      properties:
        name:
          type: string
          description: "Old item name."
        description:
          type: string
          description: "Old item description."
      required:
        - name
    listItemsHandler:
      type: object
      description: "HTTP body payload."
      additionalProperties: false
      properties:
        total:
          type: number
          description: "Total amount of items."
        items:
          type: array
          description: "Items of the current."
          items:
            type: object
            additionalProperties: false
            properties:
              id:
                type: string
              name:
                type: string
              category:
                type: string
            required:
              - id
              - name
      required:
        - total
        - items
